import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";
import qr from "../../public/qr-code.png"
import profile from "../../public/profile.png"
import Image from "next/image"
import OpenInNewIcon from '@mui/icons-material/OpenInNew';

// icons
import LocalCafeIcon from '@mui/icons-material/LocalCafe';
import AutoAwesomeIcon from '@mui/icons-material/AutoAwesome';
import AccountCircleIcon from '@mui/icons-material/AccountCircle';

import { api } from "~/utils/api";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="p-10 flex gap-10 flex-col">
        <div className="grid grid-cols-2 gap-4">
          <p className="font-semibold text-sm text-left">Good afternoon, Jeffery</p>
          <p className="text-orange-400 font-semibold text-sm text-right">100 ★</p>
        </div>
        {/* <input className="border px-5 py-2 rounded-lg" placeholder="Search..." />
        <div className="grid grid-cols-2 gap-10">
          {[0,0,0,0,0,0,0,0].map((_v, i) => 
            <div key={i} className="text-center font-semibold flex flex-col gap-4">
              <div>
                <Image src={circle} alt="Circle" />
              </div>
              <h1>Some item</h1>
            </div>
          )}
        </div> */}
        <div className="border rounded-3xl text-center p-5">
            <Image src={qr} alt="QR Code" className="w-full" />
            <p className="text-sm font-semibold">What&apos;s this?</p>
        </div>
        <div className="flex flex-row gap-6">
            <div className="w-20 h-20 bg-[url('https://upload.wikimedia.org/wikipedia/commons/c/ca/Epstein_Final_Mugshot.png')] bg-cover bg-center bg-no-repeat rounded-xl border"></div>
            {/* <Image src={profile} alt="Profile Picture" className="w-20 h-20 rounded-lg border" /> */}
            <div className="flex-1 flex flex-col gap">
                <p className="text-sm font-bold">Jeffery Epstien</p>
                <p className="text-xs font-semibold">jefferye@kids.me</p>
                <div className="text-sm rounded-full bg-gray-100 font-semibold flex-row gap-2 mt-auto py-1 px-2 w-fit inline-flex align-middle justify-center items-center">
                    <p>Edit Details</p>
                    <OpenInNewIcon className="text-xs" />
                </div>
            </div>
        </div>
        <div className="h-12"></div>
        <div className="fixed bottom-0 left-0 right-0 grid grid-cols-3 gap-10 py-5 px-10 border-t font-semibold backdrop-blur-lg bg-white bg-opacity-70">
          <div className="text-gray-500 text-center" onClick={() => window.open("/", "_self")}>
            <LocalCafeIcon className="h-8 w-8" />
            <p>Order</p>
          </div>
          <div className="text-center text-gray-500">
            <AutoAwesomeIcon className="h-8 w-8" onClick={() => window.open("/rewards", "_self")} />
            <p>Rewards</p>
          </div>
          <div className="text-center text-blue-950">
            <AccountCircleIcon className="h-8 w-8" />
            <p>Account</p>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;