import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";
import circle from "../../public/circle.png"
import Image from "next/image"

// icons
import LocalCafeIcon from '@mui/icons-material/LocalCafe';
import AutoAwesomeIcon from '@mui/icons-material/AutoAwesome';
import AccountCircleIcon from '@mui/icons-material/AccountCircle';

import { api } from "~/utils/api";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="p-10 flex gap-10 flex-col">
        <div className="grid grid-cols-2 gap-4">
          <p className="font-semibold text-sm text-left">Good afternoon, Jeffery</p>
          <p className="text-orange-400 font-semibold text-sm text-right">100 ★</p>
        </div>
        {/* <input className="border px-5 py-2 rounded-lg" placeholder="Search..." />
        <div className="grid grid-cols-2 gap-10">
          {[0,0,0,0,0,0,0,0].map((_v, i) => 
            <div key={i} className="text-center font-semibold flex flex-col gap-4">
              <div>
                <Image src={circle} alt="Circle" />
              </div>
              <h1>Some item</h1>
            </div>
          )}
        </div> */}
        <div className="h-12"></div>
        <div className="fixed bottom-0 left-0 right-0 grid grid-cols-3 gap-10 py-5 px-10 border-t font-semibold backdrop-blur-lg bg-white bg-opacity-70">
          <div className="text-gray-500 text-center">
            <LocalCafeIcon className="h-8 w-8" onClick={() => window.open("/", "_self")} />
            <p>Order</p>
          </div>
          <div className="text-center text-blue-950">
            <AutoAwesomeIcon className="h-8 w-8" />
            <p>Rewards</p>
          </div>
          <div className="text-center text-gray-500" onClick={() => window.open("/account", "_self")}>
            <AccountCircleIcon className="h-8 w-8" />
            <p>Account</p>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;